name: CI Workflow - Solo Version por Tag

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*' # ¡Este workflow solo se dispara cuando se pushea un tag como 'v1.0.0'!
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract Git tag as image version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT # Extrae 'v1.0.0' de 'refs/tags/v1.0.0'

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/conter:${{ steps.get_version.outputs.VERSION }}