name: CI Workflow

on:
  push:
    branches:
      - main 
    tags:
      - 'v*.*.*' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }} 

      - name: Extract image tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/conter 
          tags: |
            type=sha,format=long # Usa el SHA completo del commit como tag (ej: abcdef1234567890...)
            type=ref,event=branch # Para ramas, usa el nombre de la rama (ej: main)
            type=ref,event=tag # Para tags de Git, usa el nombre del tag (ej: v1.0.0)
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }} # Agrega 'latest' si es la rama main

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }} # Usa las tags generadas por 'docker/metadata-action'
          labels: ${{ steps.meta.outputs.labels }} # También puedes usar las labels generadas